### ISSUE TITLE
Items Shop and Upgrade Shop doesn't want to open

### ISSUE THREAD

**Issue by DiabolusCorporation** [boiscljo/SBA#42]
I created a map and everything is working except item shop and upgrade shop.

I am using paper 1.20.2 with Java17 and newest citizen plugin.

What am I suppose to do to fix this?

**Comment by boiscljo** [comment]
Have you tried every config "replace stores with npc" "replace store with citizens" and having both false. Just to find the exact issue

**Comment by DiabolusCorporation** [comment]
I don't understand where am I suppose to find that two

**Comment by DiabolusCorporation** [comment]
I have try turning on "replace store with citizens" and turning off "replace stores with npc" and turning off both but it still dosnt work

**Comment by purifiedfire** [comment]
For me, the team upgrades is working but the shop.yml is not... I don't get any shop.yml generating only the default one is still there... Can you provide the default shop.yml config somewhere where I can just copy and paste it to see if it works? I do see glass tinted panes when I open the SBA Shop...so it seems partially working? Thanks!

**Comment by boiscljo** [comment]
> For me, the team upgrades is working but the shop.yml is not... I don't get any shop.yml generating only the default one is still there... Can you provide the default shop.yml config somewhere where I can just copy and paste it to see if it works? I do see glass tinted panes when I open the SBA Shop...so it seems partially working? Thanks!

Github has a nice feature called search, shop.yml is in this repo. Otherwise make your own issue and do not necropost on someone else.

**Comment by purifiedfire** [comment]
> > For me, the team upgrades is working but the shop.yml is not... I don't get any shop.yml generating only the default one is still there... Can you provide the default shop.yml config somewhere where I can just copy and paste it to see if it works? I do see glass tinted panes when I open the SBA Shop...so it seems partially working? Thanks!
> 
> Github has a nice feature called search, shop.yml is in this repo. Otherwise make your own issue and do not necropost on someone else.

First off, thank you so much for the quick reply! Sorry I didn't follow the right procedure. I'm very new to this, starting up my first server and interacting on github for the first time... I was able to find the file with search (yes it is a great feature!) and that solved my issue once I reloaded as well as removed and re-added my shops. I was thinking since this issue was related to shop issues and still open, I'd post here rather create a separate issue, but good to know for future!

While following the wiki article, it did not mention anything about needing the correct shop.yml (nor was that file included in the SBA plugin folder upon install (the only file inside the shops folder was the moved-to-bedwars.txt) - Did I miss something in the documentation? Maybe those files could be included with the download and the .txt file could mention where to place them if they didn't get auto-added?
