### ISSUE TITLE
PerWorldPlugins incompatibility

### ISSUE THREAD

**Issue by TonimatasDEV** [boiscljo/SBA#7]
SBA disables when PerWorldPlugins load.

#### Server and plugin version
Spigot version: 1.19.3
BedWars version: 0.2.27.1

#### Installed plugins on server (can be obtained by `/pl`)
1. BedWars
2. PerWorldPlugins
3. SBA

#### Console log
[https://mclo.gs/6XiQyY7](https://mclo.gs/6XiQyY7)

**Comment by boiscljo** [comment]
It's required as PerWorldPlugins break custom messages handling totally breaking SBA and keeping it running end up running in huge issues making SBA unusable. The day PerWorldPlugins will fix custom message handling SBA will stop disabling. Until then it will disable to prevent people from asking support for something that CANNOT be fixed by SBA.

Closing this issue as there is NOTHING that SBA can do to fix it.
