### ISSUE TITLE
shop.yml does not contain anything

### ISSUE THREAD

**Issue by Saharsh1223** [boiscljo/SBA#88]
![Screenshot 2024-12-13 at 4 53 17 PM](https://github.com/user-attachments/assets/d2914dab-64e5-4e0d-830f-b5724b65a56f)

**Comment by Saharsh1223** [comment]
![Screenshot 2024-12-13 at 4 58 58 PM](https://github.com/user-attachments/assets/04be0771-1a09-4c4c-a430-ad4980a32f28)
i do have it all sorted and upgrades works all fine but shop.yml is not working pls help

**Comment by boiscljo** [comment]
Possible cause 1:
   you made a mistake in the syntax of the command adding the shop
Possible cause 2:
   you wrote Shop.yml instead of shop.yml in the command causing linux hosting to treat it as 2 separate files
Possible cause 3:
  some change has been made to shop.yml and 
Possible cause 4:
  you didn't use the command as mentioned on the spigot page `/bw admin (mapname) store add Store shop.yml false` causing bedward to think it's the default shop and not reading the content of shop.yml.
  
  All are users error and we encourage user to get support via discord as Issues are for proven bugs https://discord.gg/ubrdFVUyUG

**Comment by Saharsh1223** [comment]
actually, i have followed everything properly itself and those possible causes are not a mistake i made.
